# The name of your plugin as displayed in the Plugins Catalog web UI.
displayName: subfilter

# For now, `middleware` is the only type available.
type: middleware

# The import path of your plugin.
import: github.com/chahn/subfilter

# A brief description of what your plugin is doing.
summary: This middleware modifies HTTP response bodies and headers according to user-defined regular expression (regex) patterns and replacements.

# Configuration data for your plugin.
# This is mandatory,
# and Plugins Catalog will try to execute the plugin with the data you provide as part of its startup validity tests.
testData:
  replacements:
  - pattern: "Kiwi"
    replacement: "Cherry"
  - pattern: "apple(.)"
    replacement: "banana?"
    flags: "i"